Update contributing guides
rkvst/rkvst-docs pull request #671
Opened 2023-09-27 18:50 UTC by SteveLasker

Resolves #670

Includes:
- spelling errors
- dictionary to help avoid spelling errors while editing with vscode
- setting the npm version locally for local testing

2023-09-27 20:40 UTC, SteveLasker commented
cc: @beekman33

2023-09-28 11:22 UTC, pcnorth requested changes
The indentation of some of the Note sections is preventing them from displaying correctly in my browser.
I found that deleting 1 or 2 indentations for the whole block fixes it.

2023-09-28 11:22 UTC, pcnorth commented on content/contributing/getting-started/pulling-and-building-rkvst-docs/index.md
>      {{< note >}}
Delete indentation to fix the display of the Note

2023-09-28 11:22 UTC, pcnorth commented on content/contributing/adding-content/adding-articles-to-rkvst-docs/index.md
>      {{< note >}}
For some reason the indentation of this Note block breaks how it is displayed in my browser. Deleting some of the indentation fixes it.

2023-09-28 11:22 UTC, pcnorth commented on content/contributing/adding-content/adding-content-sections-to-rkvst-docs/index.md
> -    **Note:** The name of each folder should be sluggified
Again, the indentation breaks this Note

2023-09-28 22:53 UTC, SteveLasker commented
Thanks, @pcnorth, I believe I've resolved all the formatting and additional limiting fixes.

2023-09-29 19:38 UTC, mmwilder26 commented
Hello @SteveLasker   . .  . I jumped on this branch and see {{< note >}} in clear text on some of the .md files.  Is it just me seeing this or. . .?  I also see {{ < warning >}}  in clear text in one of the .md files.  Yes, did see the comment from Phil  . . . maybe these have been corrected and it's just me. . . thought I make a note that the formatting text displays for me.

2023-10-02 10:26 UTC, pcnorth approved these changes

2023-10-02 10:28 UTC, pcnorth commented
I pulled the latest changes into my local version, all the note, caution and warning sections are displaying ok.

2023-10-02 14:34 UTC, merged